# -#- coding: utf-8 -#-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from leonardo.module.web.models import Widget
from leonardo.module.web.models import Page

COLOR_CHOICES = (
    ('AliceBlue', _('AliceBlue')),
    ('AntiqueWhite', _('AntiqueWhite')),
    ('Aqua', _('Aqua')),
    ('Aquamarine', _('Aquamarine')),
    ('Azure', _('Azure')),
    ('Beige', _('Beige')),
    ('Bisque', _('Bisque')),
    ('Black', _('Black')),
    ('BlanchedAlmond', _('BlanchedAlmond')),
    ('Blue', _('Blue')),
    ('BlueViolet', _('BlueViolet')),
    ('Brown', _('Brown')),
    ('BurlyWood', _('BurlyWood')),
    ('CadetBlue', _('CadetBlue')),
    ('Chartreuse', _('Chartreuse')),
    ('Chocolate', _('Chocolate')),
    ('Coral', _('Coral')),
    ('CornflowerBlue', _('CornflowerBlue')),
    ('Cornsilk', _('Cornsilk')),
    ('Crimson', _('Crimson')),
    ('Cyan', _('Cyan')),
    ('DarkBlue', _('DarkBlue')),
    ('DarkCyan', _('DarkCyan')),
    ('DarkGoldenRod', _('DarkGoldenRod')),
    ('DarkGray', _('DarkGray')),
    ('DarkGrey', _('DarkGrey')),
    ('DarkGreen', _('DarkGreen')),
    ('DarkKhaki', _('DarkKhaki')),
    ('DarkMagenta', _('DarkMagenta')),
    ('DarkOliveGreen', _('DarkOliveGreen')),
    ('DarkOrange', _('DarkOrange')),
    ('DarkOrchid', _('DarkOrchid')),
    ('DarkRed', _('DarkRed')),
    ('DarkSalmon', _('DarkSalmon')),
    ('DarkSeaGreen', _('DarkSeaGreen')),
    ('DarkSlateBlue', _('DarkSlateBlue')),
    ('DarkSlateGray', _('DarkSlateGray')),
    ('DarkSlateGrey', _('DarkSlateGrey')),
    ('DarkTurquoise', _('DarkTurquoise')),
    ('DarkViolet', _('DarkViolet')),
    ('DeepPink', _('DeepPink')),
    ('DeepSkyBlue', _('DeepSkyBlue')),
    ('DimGray', _('DimGray')),
    ('DimGrey', _('DimGrey')),
    ('DodgerBlue', _('DodgerBlue')),
    ('FireBrick', _('FireBrick')),
    ('FloralWhite', _('FloralWhite')),
    ('ForestGreen', _('ForestGreen')),
    ('Fuchsia', _('Fuchsia')),
    ('Gainsboro', _('Gainsboro')),
    ('GhostWhite', _('GhostWhite')),
    ('Gold', _('Gold')),
    ('GoldenRod', _('GoldenRod')),
    ('Gray', _('Gray')),
    ('Grey', _('Grey')),
    ('Green', _('Green')),
    ('GreenYellow', _('GreenYellow')),
    ('HoneyDew', _('HoneyDew')),
    ('HotPink', _('HotPink')),
    ('IndianRed', _('IndianRed')),
    ('Indigo', _('Indigo')),
    ('Ivory', _('Ivory')),
    ('Khaki', _('Khaki')),
    ('Lavender', _('Lavender')),
    ('LavenderBlush', _('LavenderBlush')),
    ('LawnGreen', _('LawnGreen')),
    ('LemonChiffon', _('LemonChiffon')),
    ('LightBlue', _('LightBlue')),
    ('LightCoral', _('LightCoral')),
    ('LightCyan', _('LightCyan')),
    ('LightGoldenRodYellow', _('LightGoldenRodYellow')),
    ('LightGray', _('LightGray')),
    ('LightGrey', _('LightGrey')),
    ('LightGreen', _('LightGreen')),
    ('LightPink', _('LightPink')),
    ('LightSalmon', _('LightSalmon')),
    ('LightSeaGreen', _('LightSeaGreen')),
    ('LightSkyBlue', _('LightSkyBlue')),
    ('LightSlateGray', _('LightSlateGray')),
    ('LightSlateGrey', _('LightSlateGrey')),
    ('LightSteelBlue', _('LightSteelBlue')),
    ('LightYellow', _('LightYellow')),
    ('Lime', _('Lime')),
    ('LimeGreen', _('LimeGreen')),
    ('Linen', _('Linen')),
    ('Magenta', _('Magenta')),
    ('Maroon', _('Maroon')),
    ('MediumAquaMarine', _('MediumAquaMarine')),
    ('MediumBlue', _('MediumBlue')),
    ('MediumOrchid', _('MediumOrchid')),
    ('MediumPurple', _('MediumPurple')),
    ('MediumSeaGreen', _('MediumSeaGreen')),
    ('MediumSlateBlue', _('MediumSlateBlue')),
    ('MediumSpringGreen', _('MediumSpringGreen')),
    ('MediumTurquoise', _('MediumTurquoise')),
    ('MediumVioletRed', _('MediumVioletRed')),
    ('MidnightBlue', _('MidnightBlue')),
    ('MintCream', _('MintCream')),
    ('MistyRose', _('MistyRose')),
    ('Moccasin', _('Moccasin')),
    ('NavajoWhite', _('NavajoWhite')),
    ('Navy', _('Navy')),
    ('OldLace', _('OldLace')),
    ('Olive', _('Olive')),
    ('OliveDrab', _('OliveDrab')),
    ('Orange', _('Orange')),
    ('OrangeRed', _('OrangeRed')),
    ('Orchid', _('Orchid')),
    ('PaleGoldenRod', _('PaleGoldenRod')),
    ('PaleGreen', _('PaleGreen')),
    ('PaleTurquoise', _('PaleTurquoise')),
    ('PaleVioletRed', _('PaleVioletRed')),
    ('PapayaWhip', _('PapayaWhip')),
    ('PeachPuff', _('PeachPuff')),
    ('Peru', _('Peru')),
    ('Pink', _('Pink')),
    ('Plum', _('Plum')),
    ('PowderBlue', _('PowderBlue')),
    ('Purple', _('Purple')),
    ('RebeccaPurple', _('RebeccaPurple')),
    ('Red', _('Red')),
    ('RosyBrown', _('RosyBrown')),
    ('RoyalBlue', _('RoyalBlue')),
    ('SaddleBrown', _('SaddleBrown')),
    ('Salmon', _('Salmon')),
    ('SandyBrown', _('SandyBrown')),
    ('SeaGreen', _('SeaGreen')),
    ('SeaShell', _('SeaShell')),
    ('Sienna', _('Sienna')),
    ('Silver', _('Silver')),
    ('SkyBlue', _('SkyBlue')),
    ('SlateBlue', _('SlateBlue')),
    ('SlateGray', _('SlateGray')),
    ('SlateGrey', _('SlateGrey')),
    ('Snow', _('Snow')),
    ('SpringGreen', _('SpringGreen')),
    ('SteelBlue', _('SteelBlue')),
    ('Tan', _('Tan')),
    ('Teal', _('Teal')),
    ('Thistle', _('Thistle')),
    ('Tomato', _('Tomato')),
    ('Turquoise', _('Turquoise')),
    ('Violet', _('Violet')),
    ('Wheat', _('Wheat')),
    ('White', _('White')),
    ('WhiteSmoke', _('WhiteSmoke')),
    ('Yellow', _('Yellow')),
    ('YellowGreen', _('YellowGreen')),
)

POSITION_CHOICES = (
    ('margin: 0 auto;', _('Center')),
)

class MultiCalculatorWidget(Widget):

    colorth = models.CharField(verbose_name=_("Color of table head"), max_length=255, blank=True, choices=COLOR_CHOICES)
    colorthActive = models.CharField(verbose_name=_("Color of active table head"), max_length=255, blank=True, choices=COLOR_CHOICES)
    position = models.CharField(verbose_name=_("Position"), max_length=255, blank=True, choices=POSITION_CHOICES)

    class Meta:
        abstract = True
        verbose_name = _('Multi Calc')
        verbose_name_plural = _('Multi Calcs')